#!/bin/bash

INSTANCE_NAME='cmu95737-db-host'
INSTANCE_COUNT=$(aws ec2 describe-instances --filters Name='tag:Name',Values=${INSTANCE_NAME} Name=instance-state-name,Values=running | jq -r '.Reservations' | jq length)

if [[ ${INSTANCE_COUNT} -eq 0 ]]; then
  echo "No VM detected! Exiting..."
  return 1

elif [[ ! ${INSTANCE_COUNT} -eq 1 ]]; then
  echo "Unexpected count of VMs detected! Exiting..."
  return 1

fi

INSTANCE_IP=$(aws ec2 describe-instances --filters Name='tag:Name',Values=${INSTANCE_NAME} Name=instance-state-name,Values=running | jq -r '.Reservations[].Instances[] | .PublicIpAddress')
ssh -i ~/cmu95737.pem "ubuntu@${INSTANCE_IP}"

